Add invalid CARCH check to catch when people are running vbuild manually

diff --git a/packages/tailscale/VELBUILD b/packages/tailscale/VELBUILD
--- a/packages/tailscale/VELBUILD
+++ b/packages/tailscale/VELBUILD
@@ -30,8 +30,12 @@ unpack() {
 	fi
 
 	case "$CARCH" in
-		aarch64) _arch="arm64" ;;
-		armv7) _arch="arm" ;;
+	aarch64) _arch="arm64" ;;
+	armv7) _arch="arm" ;;
+	*)
+		echo "Invalid CARCH: $CARCH"
+		exit 1
+		;;
 	esac
 
 	mkdir -p "$srcdir"
diff --git a/packages/tripletap/VELBUILD b/packages/tripletap/VELBUILD
--- a/packages/tripletap/VELBUILD
+++ b/packages/tripletap/VELBUILD
@@ -30,6 +30,10 @@ package() {
 	armv7)
 		install -Dm755 evtest.arm32 "$install_dir/evtest"
 		;;
+	*)
+		echo "Invalid CARCH: $CARCH"
+		exit 1
+		;;
 	esac
 
 	install -Dm755 main.sh "$install_dir/main.sh"
