Switch to building upstream tilem from source

diff --git a/packages/tilem/VELBUILD b/packages/tilem/VELBUILD
--- a/packages/tilem/VELBUILD
+++ b/packages/tilem/VELBUILD
@@ -1,66 +1,96 @@
 maintainer="Nathaniel van Diepen <eeems@eeems.codes>"
 pkgname=tilem
 pkgver=0.1.3_git6
+pkgver=0.1.3
 pkgrel=3
 upstream_author="timower"
 category="apps"
 pkgdesc="A TI-84+ calculator emulator for the remarkable."
-url="https://github.com/timower/rM2-stuff"
+url="https://github.com/$upstream_author/rM2-stuff"
 arch="aarch64 armv7"
 license="GPL-3.0"
 depends="appload curl"
 options="!check !fhs !strip !tracedeps"
-readmeurl="https://raw.githubusercontent.com/$upstream_author/rM2-stuff/v0.1.3/Readme.md"
+readmeurl="https://raw.githubusercontent.com/$upstream_author/rM2-stuff/v$pkgver/Readme.md"
 
 source="
-https://github.com/notfrants/vellum-builds/releases/download/v0.1.0/tilem-aarch64.tar.gz
-https://github.com/notfrants/vellum-builds/releases/download/v0.1.0/tilem-arm32.tar.gz
+$pkgname-$pkgver.tar.gz::https://github.com/$upstream_author/rM2-stuff/archive/refs/tags/v$pkgver.tar.gz
+external.manifest.json
+rm-toolchain.cmake
 "
 
-unpack() {
+prepare() {
+	default_prepare
+	apk add --no-cache git-lfs
+	cd "$srcdir/rM2-stuff-$pkgver"
+	mkdir -p tilem
+	cd tilem
+	git config set --global advice.defaultBranchName false
+	git init
+	git lfs install
+	git remote add origin https://github.com/timower/rM2-stuff.git
+	git fetch --depth 1 origin tag v$pkgver --no-tags
+	git checkout v$pkgver
+	git lfs fetch
+	git lfs checkout
+}
+image() {
 	case "$CARCH" in
-	aarch64) tar -xzf "$srcdir"/tilem-aarch64.tar.gz -C "$srcdir" ;;
-	armv7) tar -xzf "$srcdir"/tilem-arm32.tar.gz -C "$srcdir" ;;
+	aarch64) echo "eeems/remarkable-toolchain:5.6.75-rmpp" ;;
+	armv7) echo "eeems/remarkable-toolchain:5.6.75-rm2" ;;
+	*)
+		echo "Invalid CARCH: $CARCH"
+		exit 1
+		;;
 	esac
+}
+build() {
+	set -e
+	. /opt/codex/*/*/environment-setup-*
+	export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
+	cd "$srcdir/rM2-stuff-$pkgver"
+	ln -sf "$startdir"/rm-toolchain.cmake cmake/rm-toolchain.cmake
+	ln -sf "$startdir"/rm-toolchain.cmake tilem/cmake/rm-toolchain.cmake
+	sed -i 's|CMAKE_SYSTEM_PROCESSOR|ENV{ARCH}|' \
+		vendor/frida/CMakeLists.txt
+	sed -i 's|wget -O|/home/root/.vellum/bin/curl -Lfo|' \
+		apps/tilem/Dialog.cpp
+	mkdir install
+	cd tilem
+	cmake --preset release
+	cmake \
+		--build build/release \
+		--target tilem
+	cmake \
+		--install build/release \
+		--prefix ../install \
+		--component tilem \
+		--strip
 }
 
 package() {
-	install -Dm755 "$srcdir"/tilem \
+	cd "$srcdir/rM2-stuff-$pkgver"
+	install -Dm644 "LICENSE" \
+		"$pkgdir"/home/root/.vellum/licenses/"$pkgname"/LICENSE
+	echo "https://github.com/$upstream_author/$pkgname" > \
+		"$pkgdir/home/root/.vellum/licenses/$pkgname/SOURCES"
+
+	install -Dm755 install/bin/tilem \
 		"$pkgdir"/home/root/xovi/exthome/appload/tilem/tilem
-
-	install -Dm644 "$srcdir"/external.manifest.json \
-		"$pkgdir"/home/root/xovi/exthome/appload/tilem/external.manifest.json
-	install -Dm644 "$srcdir"/icon.png \
+	install -Dm755 install/etc/draft/icons/tilem.png \
 		"$pkgdir"/home/root/xovi/exthome/appload/tilem/icon.png
-
-	install -Dm644 "$srcdir"/LICENSE \
-		"$pkgdir"/home/root/.vellum/licenses/$pkgname/LICENSE
-	install -Dm644 "$srcdir"/SOURCES \
-		"$pkgdir"/home/root/.vellum/licenses/$pkgname/SOURCES
-}
-
-postinstall() {
-	echo ""
-	echo "================================================"
-	echo "  NOTE: To use TilEm, you must refresh AppLoad"
-	echo "================================================"
-	echo ""
+	install -Dm755 "$startdir"/external.manifest.json \
+		"$pkgdir"/home/root/xovi/exthome/appload/tilem/external.manifest.json
 }
 
 postdeinstall() {
 	if [ "$VELLUM_PURGE" = "1" ]; then
 		rm -rf /home/root/xovi/exthome/appload/tilem
 	fi
-
-	echo ""
-	echo "================================================="
-	echo "  NOTE: You must refresh AppLoad to see changes"
-	echo "  reflected in the tablet UI"
-	echo "================================================="
-	echo ""
 }
-
-sha512sums="
-462a21c0f440cc789fc383461f219cb8ccea968de03b278d1ef501eddad8995823febad468a5b7133ff2f97f3d7da08edac6787f496bdff554558f92e5e9a470  tilem-aarch64.tar.gz
-7d8a159bd0294cabb29ab2e5cd5feaac8005462278b1e60d87af8e44cc540ca7f937cbcedea200beb3eb0b898083dc9427b0f14d039d2e3cc1b5b74337bc03c5  tilem-arm32.tar.gz
-"
+sha512sums='5dab2bd2f84222737b8b25dd899527cc58879e313e1eabbd41961d4497a8fdc17ae62e9aaf914cbe56abe319bd2f78cc88bf401f40d00942e860d8694d40da7e
+tilem-0.1.3.tar.gz
+79c5dda363d5d362b4b89f89bda598fb4b7bcb1158568ca753db19c120a31c07bdc181ef23c857ec0c28194b60ee4063cc8fc8b0f9f0910575d744e1006faaca
+external.manifest.json
+a501914f2bae72334f9502506d3c3548402788dd70926b17bb4eb66d8b42031e4627d235af9a8d41396fb6a5267acad1f3fef2c87e2d7601af90e95a65f66656
+rm-toolchain.cmake'
